//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TODConfiguration {
    
    private TODConfigurationFutureReadCommand futureReadCommandField;
    
    private TODConfigurationCurrentReadCommand currentReadCommandField;

    private TODConfigurationReadCommandSP todConfigureReadCommandSP;
    
    private string writeCommandField;

    private TODConfigurationPushParameterRead pushParameterReadField;

    private TODConfigurationPushParameterWrite pushParameterWriteField;

    private TODConfigurationScrollParameterRead scrollParameterReadField;

    private TODConfigurationScrollParameterWrite scrollParameterWriteField;

    private TODConfigurationHighParameterRead highParameterReadField;

    private TODConfigurationHighParameterWrite highParameterWriteField;


    public TODConfigurationReadCommandSP ReadCommandSP
    {
        get
        {
            return this.todConfigureReadCommandSP;
        }
        set
        {
            this.todConfigureReadCommandSP = value;
        }
    }
    

    /// <remarks/>
    public TODConfigurationFutureReadCommand FutureReadCommand {
        get {
            return this.futureReadCommandField;
        }
        set {
            this.futureReadCommandField = value;
        }
    }
    
    /// <remarks/>
    public TODConfigurationCurrentReadCommand CurrentReadCommand {
        get {
            return this.currentReadCommandField;
        }
        set {
            this.currentReadCommandField = value;
        }
    }
    
    /// <remarks/>
    public string WriteCommand {
        get {
            return this.writeCommandField;
        }
        set {
            this.writeCommandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PushParameterRead", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TODConfigurationPushParameterRead PushParameterRead
    {
        get
        {
            return this.pushParameterReadField;
        }
        set
        {
            this.pushParameterReadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PushParameterWrite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TODConfigurationPushParameterWrite PushParameterWrite
    {
        get
        {
            return this.pushParameterWriteField;
        }
        set
        {
            this.pushParameterWriteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ScrollParameterRead", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TODConfigurationScrollParameterRead ScrollParameterRead
    {
        get
        {
            return this.scrollParameterReadField;
        }
        set
        {
            this.scrollParameterReadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ScrollParameterWrite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TODConfigurationScrollParameterWrite ScrollParameterWrite
    {
        get
        {
            return this.scrollParameterWriteField;
        }
        set
        {
            this.scrollParameterWriteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HighParameterRead", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TODConfigurationHighParameterRead HighParameterRead
    {
        get
        {
            return this.highParameterReadField;
        }
        set
        {
            this.highParameterReadField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HighParameterWrite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TODConfigurationHighParameterWrite HighParameterWrite
    {
        get
        {
            return this.highParameterWriteField;
        }
        set
        {
            this.highParameterWriteField = value;
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TODConfigurationFutureReadCommand {
    
    private string s1D1Field;
    
    private string s1D2Field;
    
    private string s1D3Field;
    
    private string s1D4Field;
    
    private string s1D5Field;
    
    private string s1D6Field;
    
    private string s1AcDateField;
    
    private string s2D1Field;
    
    private string s2D2Field;
    
    private string s2D3Field;
    
    private string s2D4Field;
    
    private string s2D5Field;
    
    private string s2D6Field;
    
    private string s2AcDateField;
    
    private string s3D1Field;
    
    private string s3D2Field;
    
    private string s3D3Field;
    
    private string s3D4Field;
    
    private string s3D5Field;
    
    private string s3D6Field;
    
    private string s3AcDateField;
    
    private string s4D1Field;
    
    private string s4D2Field;
    
    private string s4D3Field;
    
    private string s4D4Field;
    
    private string s4D5Field;
    
    private string s4D6Field;
    
    private string s4AcDateField;
    
    private string h1Field;
    
    private string h2Field;
    
    private string h3Field;
    
    private string h4Field;
    
    private string h5Field;
    
    private string h6Field;
    
    private string h7Field;
    
    private string h8Field;
    
    private string h9Field;
    
    private string h10Field;
    
    private string hAcDateField;
    
    /// <remarks/>
    public string S1D1 {
        get {
            return this.s1D1Field;
        }
        set {
            this.s1D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D2 {
        get {
            return this.s1D2Field;
        }
        set {
            this.s1D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D3 {
        get {
            return this.s1D3Field;
        }
        set {
            this.s1D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D4 {
        get {
            return this.s1D4Field;
        }
        set {
            this.s1D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D5 {
        get {
            return this.s1D5Field;
        }
        set {
            this.s1D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D6 {
        get {
            return this.s1D6Field;
        }
        set {
            this.s1D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S1AcDate {
        get {
            return this.s1AcDateField;
        }
        set {
            this.s1AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string S2D1 {
        get {
            return this.s2D1Field;
        }
        set {
            this.s2D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D2 {
        get {
            return this.s2D2Field;
        }
        set {
            this.s2D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D3 {
        get {
            return this.s2D3Field;
        }
        set {
            this.s2D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D4 {
        get {
            return this.s2D4Field;
        }
        set {
            this.s2D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D5 {
        get {
            return this.s2D5Field;
        }
        set {
            this.s2D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D6 {
        get {
            return this.s2D6Field;
        }
        set {
            this.s2D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S2AcDate {
        get {
            return this.s2AcDateField;
        }
        set {
            this.s2AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string S3D1 {
        get {
            return this.s3D1Field;
        }
        set {
            this.s3D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D2 {
        get {
            return this.s3D2Field;
        }
        set {
            this.s3D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D3 {
        get {
            return this.s3D3Field;
        }
        set {
            this.s3D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D4 {
        get {
            return this.s3D4Field;
        }
        set {
            this.s3D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D5 {
        get {
            return this.s3D5Field;
        }
        set {
            this.s3D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D6 {
        get {
            return this.s3D6Field;
        }
        set {
            this.s3D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S3AcDate {
        get {
            return this.s3AcDateField;
        }
        set {
            this.s3AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string S4D1 {
        get {
            return this.s4D1Field;
        }
        set {
            this.s4D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D2 {
        get {
            return this.s4D2Field;
        }
        set {
            this.s4D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D3 {
        get {
            return this.s4D3Field;
        }
        set {
            this.s4D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D4 {
        get {
            return this.s4D4Field;
        }
        set {
            this.s4D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D5 {
        get {
            return this.s4D5Field;
        }
        set {
            this.s4D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D6 {
        get {
            return this.s4D6Field;
        }
        set {
            this.s4D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S4AcDate {
        get {
            return this.s4AcDateField;
        }
        set {
            this.s4AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string H1 {
        get {
            return this.h1Field;
        }
        set {
            this.h1Field = value;
        }
    }
    
    /// <remarks/>
    public string H2 {
        get {
            return this.h2Field;
        }
        set {
            this.h2Field = value;
        }
    }
    
    /// <remarks/>
    public string H3 {
        get {
            return this.h3Field;
        }
        set {
            this.h3Field = value;
        }
    }
    
    /// <remarks/>
    public string H4 {
        get {
            return this.h4Field;
        }
        set {
            this.h4Field = value;
        }
    }
    
    /// <remarks/>
    public string H5 {
        get {
            return this.h5Field;
        }
        set {
            this.h5Field = value;
        }
    }
    
    /// <remarks/>
    public string H6 {
        get {
            return this.h6Field;
        }
        set {
            this.h6Field = value;
        }
    }
    
    /// <remarks/>
    public string H7 {
        get {
            return this.h7Field;
        }
        set {
            this.h7Field = value;
        }
    }
    
    /// <remarks/>
    public string H8 {
        get {
            return this.h8Field;
        }
        set {
            this.h8Field = value;
        }
    }
    
    /// <remarks/>
    public string H9 {
        get {
            return this.h9Field;
        }
        set {
            this.h9Field = value;
        }
    }
    
    /// <remarks/>
    public string H10 {
        get {
            return this.h10Field;
        }
        set {
            this.h10Field = value;
        }
    }
    
    /// <remarks/>
    public string HAcDate {
        get {
            return this.hAcDateField;
        }
        set {
            this.hAcDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TODConfigurationCurrentReadCommand {
    
    private string s1D1Field;
    
    private string s1D2Field;
    
    private string s1D3Field;
    
    private string s1D4Field;
    
    private string s1D5Field;
    
    private string s1D6Field;
    
    private string s1AcDateField;
    
    private string s2D1Field;
    
    private string s2D2Field;
    
    private string s2D3Field;
    
    private string s2D4Field;
    
    private string s2D5Field;
    
    private string s2D6Field;
    
    private string s2AcDateField;
    
    private string s3D1Field;
    
    private string s3D2Field;
    
    private string s3D3Field;
    
    private string s3D4Field;
    
    private string s3D5Field;
    
    private string s3D6Field;
    
    private string s3AcDateField;
    
    private string s4D1Field;
    
    private string s4D2Field;
    
    private string s4D3Field;
    
    private string s4D4Field;
    
    private string s4D5Field;
    
    private string s4D6Field;
    
    private string s4AcDateField;
    
    private string h1Field;
    
    private string h2Field;
    
    private string h3Field;
    
    private string h4Field;
    
    private string h5Field;
    
    private string h6Field;
    
    private string h7Field;
    
    private string h8Field;
    
    private string h9Field;
    
    private string h10Field;
    
    private string hAcDateField;
    
    /// <remarks/>
    public string S1D1 {
        get {
            return this.s1D1Field;
        }
        set {
            this.s1D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D2 {
        get {
            return this.s1D2Field;
        }
        set {
            this.s1D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D3 {
        get {
            return this.s1D3Field;
        }
        set {
            this.s1D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D4 {
        get {
            return this.s1D4Field;
        }
        set {
            this.s1D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D5 {
        get {
            return this.s1D5Field;
        }
        set {
            this.s1D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S1D6 {
        get {
            return this.s1D6Field;
        }
        set {
            this.s1D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S1AcDate {
        get {
            return this.s1AcDateField;
        }
        set {
            this.s1AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string S2D1 {
        get {
            return this.s2D1Field;
        }
        set {
            this.s2D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D2 {
        get {
            return this.s2D2Field;
        }
        set {
            this.s2D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D3 {
        get {
            return this.s2D3Field;
        }
        set {
            this.s2D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D4 {
        get {
            return this.s2D4Field;
        }
        set {
            this.s2D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D5 {
        get {
            return this.s2D5Field;
        }
        set {
            this.s2D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S2D6 {
        get {
            return this.s2D6Field;
        }
        set {
            this.s2D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S2AcDate {
        get {
            return this.s2AcDateField;
        }
        set {
            this.s2AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string S3D1 {
        get {
            return this.s3D1Field;
        }
        set {
            this.s3D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D2 {
        get {
            return this.s3D2Field;
        }
        set {
            this.s3D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D3 {
        get {
            return this.s3D3Field;
        }
        set {
            this.s3D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D4 {
        get {
            return this.s3D4Field;
        }
        set {
            this.s3D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D5 {
        get {
            return this.s3D5Field;
        }
        set {
            this.s3D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S3D6 {
        get {
            return this.s3D6Field;
        }
        set {
            this.s3D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S3AcDate {
        get {
            return this.s3AcDateField;
        }
        set {
            this.s3AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string S4D1 {
        get {
            return this.s4D1Field;
        }
        set {
            this.s4D1Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D2 {
        get {
            return this.s4D2Field;
        }
        set {
            this.s4D2Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D3 {
        get {
            return this.s4D3Field;
        }
        set {
            this.s4D3Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D4 {
        get {
            return this.s4D4Field;
        }
        set {
            this.s4D4Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D5 {
        get {
            return this.s4D5Field;
        }
        set {
            this.s4D5Field = value;
        }
    }
    
    /// <remarks/>
    public string S4D6 {
        get {
            return this.s4D6Field;
        }
        set {
            this.s4D6Field = value;
        }
    }
    
    /// <remarks/>
    public string S4AcDate {
        get {
            return this.s4AcDateField;
        }
        set {
            this.s4AcDateField = value;
        }
    }
    
    /// <remarks/>
    public string H1 {
        get {
            return this.h1Field;
        }
        set {
            this.h1Field = value;
        }
    }
    
    /// <remarks/>
    public string H2 {
        get {
            return this.h2Field;
        }
        set {
            this.h2Field = value;
        }
    }
    
    /// <remarks/>
    public string H3 {
        get {
            return this.h3Field;
        }
        set {
            this.h3Field = value;
        }
    }
    
    /// <remarks/>
    public string H4 {
        get {
            return this.h4Field;
        }
        set {
            this.h4Field = value;
        }
    }
    
    /// <remarks/>
    public string H5 {
        get {
            return this.h5Field;
        }
        set {
            this.h5Field = value;
        }
    }
    
    /// <remarks/>
    public string H6 {
        get {
            return this.h6Field;
        }
        set {
            this.h6Field = value;
        }
    }
    
    /// <remarks/>
    public string H7 {
        get {
            return this.h7Field;
        }
        set {
            this.h7Field = value;
        }
    }
    
    /// <remarks/>
    public string H8 {
        get {
            return this.h8Field;
        }
        set {
            this.h8Field = value;
        }
    }
    
    /// <remarks/>
    public string H9 {
        get {
            return this.h9Field;
        }
        set {
            this.h9Field = value;
        }
    }
    
    /// <remarks/>
    public string H10 {
        get {
            return this.h10Field;
        }
        set {
            this.h10Field = value;
        }
    }
    
    /// <remarks/>
    public string HAcDate {
        get {
            return this.hAcDateField;
        }
        set {
            this.hAcDateField = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TODConfigurationReadCommandSP
{

    private string r4D400Field;

    private string r4D401Field;

    private string r4D402Field;

    private string r4D403Field;

    private string r4D404Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4D400
    {
        get
        {
            return this.r4D400Field;
        }
        set
        {
            this.r4D400Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4D401
    {
        get
        {
            return this.r4D401Field;
        }
        set
        {
            this.r4D401Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4D402
    {
        get
        {
            return this.r4D402Field;
        }
        set
        {
            this.r4D402Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4D403
    {
        get
        {
            return this.r4D403Field;
        }
        set
        {
            this.r4D403Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4D404
    {
        get
        {
            return this.r4D404Field;
        }
        set
        {
            this.r4D404Field = value;
        }
    }
}




/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TODConfigurationPushParameterRead
{

    private string r1Field;

    private string r2Field;

    private string r3Field;

    private string r4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R1
    {
        get
        {
            return this.r1Field;
        }
        set
        {
            this.r1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R2
    {
        get
        {
            return this.r2Field;
        }
        set
        {
            this.r2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R3
    {
        get
        {
            return this.r3Field;
        }
        set
        {
            this.r3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4
    {
        get
        {
            return this.r4Field;
        }
        set
        {
            this.r4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TODConfigurationPushParameterWrite
{

    private string w1Field;

    private string w2Field;

    private string w3Field;

    private string w4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W1
    {
        get
        {
            return this.w1Field;
        }
        set
        {
            this.w1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W2
    {
        get
        {
            return this.w2Field;
        }
        set
        {
            this.w2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W3
    {
        get
        {
            return this.w3Field;
        }
        set
        {
            this.w3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W4
    {
        get
        {
            return this.w4Field;
        }
        set
        {
            this.w4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TODConfigurationScrollParameterRead
{

    private string r1Field;

    private string r2Field;

    private string r3Field;

    private string r4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R1
    {
        get
        {
            return this.r1Field;
        }
        set
        {
            this.r1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R2
    {
        get
        {
            return this.r2Field;
        }
        set
        {
            this.r2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R3
    {
        get
        {
            return this.r3Field;
        }
        set
        {
            this.r3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4
    {
        get
        {
            return this.r4Field;
        }
        set
        {
            this.r4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TODConfigurationScrollParameterWrite
{

    private string w1Field;

    private string w2Field;

    private string w3Field;

    private string w4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W1
    {
        get
        {
            return this.w1Field;
        }
        set
        {
            this.w1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W2
    {
        get
        {
            return this.w2Field;
        }
        set
        {
            this.w2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W3
    {
        get
        {
            return this.w3Field;
        }
        set
        {
            this.w3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W4
    {
        get
        {
            return this.w4Field;
        }
        set
        {
            this.w4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TODConfigurationHighParameterRead
{

    private string r1Field;

    private string r2Field;

    private string r3Field;

    private string r4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R1
    {
        get
        {
            return this.r1Field;
        }
        set
        {
            this.r1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R2
    {
        get
        {
            return this.r2Field;
        }
        set
        {
            this.r2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R3
    {
        get
        {
            return this.r3Field;
        }
        set
        {
            this.r3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string R4
    {
        get
        {
            return this.r4Field;
        }
        set
        {
            this.r4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TODConfigurationHighParameterWrite
{

    private string w1Field;

    private string w2Field;

    private string w3Field;

    private string w4Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W1
    {
        get
        {
            return this.w1Field;
        }
        set
        {
            this.w1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W2
    {
        get
        {
            return this.w2Field;
        }
        set
        {
            this.w2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W3
    {
        get
        {
            return this.w3Field;
        }
        set
        {
            this.w3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string W4
    {
        get
        {
            return this.w4Field;
        }
        set
        {
            this.w4Field = value;
        }
    }
}
