//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MeterOfflineConfigSettings {
    
    private MeterOfflineConfigSettingsMeterConfigElement[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeterConfigElement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MeterOfflineConfigSettingsMeterConfigElement[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MeterOfflineConfigSettingsMeterConfigElement {
    
    private string dIPField;
    
    private string sIPField;
    
    private string kvahSelectionField;
    
    private string displayParametersField;
    
    private string displayParametersIECField;
    
    private string tODField;
    
    private string rTCField;
    
    private string cTRatioField;
    
    private string pTRatioField;
    
    private string billingTypeField;
    
    private string billingResetField;
    
    private string lockRS232Field;
    
    private string autoLockField;
    
    private string dailyLogField;
    
    private string magneticTamperIconField;
    
    private string dIPWithSlidingField;
    
    private string manualBillingField;
    
    private string softwareBillingField;
    
    private string loadControlField;
    
    private string loadControl1PSmartMeterField;
    
    private string disconnectControlField;
    
    private string rS485Field;
    
    private string meterModelField;
    
    private string firmwareField;

    private string pulseEnergyField;
    private string manualButtonMDResetField;    

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DIP {
        get {
            return this.dIPField;
        }
        set {
            this.dIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SIP {
        get {
            return this.sIPField;
        }
        set {
            this.sIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string KvahSelection {
        get {
            return this.kvahSelectionField;
        }
        set {
            this.kvahSelectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisplayParameters {
        get {
            return this.displayParametersField;
        }
        set {
            this.displayParametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisplayParametersIEC {
        get {
            return this.displayParametersIECField;
        }
        set {
            this.displayParametersIECField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TOD {
        get {
            return this.tODField;
        }
        set {
            this.tODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RTC {
        get {
            return this.rTCField;
        }
        set {
            this.rTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CTRatio {
        get {
            return this.cTRatioField;
        }
        set {
            this.cTRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PTRatio {
        get {
            return this.pTRatioField;
        }
        set {
            this.pTRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillingType {
        get {
            return this.billingTypeField;
        }
        set {
            this.billingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillingReset {
        get {
            return this.billingResetField;
        }
        set {
            this.billingResetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LockRS232 {
        get {
            return this.lockRS232Field;
        }
        set {
            this.lockRS232Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AutoLock {
        get {
            return this.autoLockField;
        }
        set {
            this.autoLockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DailyLog {
        get {
            return this.dailyLogField;
        }
        set {
            this.dailyLogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MagneticTamperIcon {
        get {
            return this.magneticTamperIconField;
        }
        set {
            this.magneticTamperIconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DIPWithSliding {
        get {
            return this.dIPWithSlidingField;
        }
        set {
            this.dIPWithSlidingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ManualBilling {
        get {
            return this.manualBillingField;
        }
        set {
            this.manualBillingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SoftwareBilling {
        get {
            return this.softwareBillingField;
        }
        set {
            this.softwareBillingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadControl {
        get {
            return this.loadControlField;
        }
        set {
            this.loadControlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadControl1PSmartMeter {
        get {
            return this.loadControl1PSmartMeterField;
        }
        set {
            this.loadControl1PSmartMeterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisconnectControl {
        get {
            return this.disconnectControlField;
        }
        set {
            this.disconnectControlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RS485 {
        get {
            return this.rS485Field;
        }
        set {
            this.rS485Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MeterModel {
        get {
            return this.meterModelField;
        }
        set {
            this.meterModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Firmware {
        get {
            return this.firmwareField;
        }
        set {
            this.firmwareField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PulseEnergy
    {
        get
        {
            return this.pulseEnergyField;
        }
        set
        {
            this.pulseEnergyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ManualButtonMDReset
    {
        get
        {
            return this.manualButtonMDResetField;
        }
        set
        {
            this.manualButtonMDResetField = value;
        }
    }


}
