//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DLMSGSMCommunication
{



    public class MultipleSerialPortSettings
    {

        public static volatile MultipleSerialPortSettings instance;
        private static object syncRoot = new Object();
        private string serialPort = "COM1";
        private string signOnBaudRate = "300";
        private string commandBaudRate = "9600";
        private string stopBits = "1";
        private string dataBits = "8";
        private string parity = "None";
        private int interframeTimeout = 5000;
        private int serverSAP = 1;
        private int serverLowerMacAddress = 256;
        private byte applicationContext = 1;
        private int pduSize = 9999;
        private byte cnf1 = 0;
        private byte cnf2 = 0;
        private byte cnf3 = 0;
        private string readOut = "C:\\Program Files\\Cabcon\\DLMS MMP\\Configuration\\Instantaneous_c.xml";
        private string billing = "C:\\Program Files\\Cabcon\\DLMS MMP\\Configuration\\Billing.xml";
        private string billingVZ = "C:\\Program Files\\Cabcon\\DLMS MMP\\Configuration\\BillingVZ.xml";
        private string tamperXML = "C:\\Program Files\\Cabcon\\DLMS MMP\\Configuration\\Tamper.xml";
        private string communicationPort = "RJ Port";
        private string communicationMode = "Mode-E";
        private string modemNumber = "";
        private string scaleXMLPath = "C:\\Program Files\\Cabcon\\DLMS MMP\\Configuration";
        private string hlsKey = "F26CE01A15BD16CBB03B473F65E3BFBA";
        private int clientSAP = 32;
        private int commandTimeOut = 5500;
        private int intercharacterDelay = 5000;
        private byte securityMechanism = 0;
        private string password = "11111111";
        private int maxLoadSurveyDays = 0;
        public static MultipleSerialPortSettings Default
        {
            get
            {
                if (instance == null)
                {
                    lock (syncRoot)
                    {
                        if (instance == null)
                        {
                            instance = new MultipleSerialPortSettings();
                        }
                    }
                }
                return instance;
            }
        }


        public string SerialPort
        {
            get
            {
                return serialPort;
            }
            set
            {
                serialPort = value;
            }
        }


        public string SignOnBaudRate
        {
            get
            {
                return signOnBaudRate;
            }
            set
            {
                signOnBaudRate = value;
            }
        }


        public string CommandBaudRate
        {
            get
            {
                return commandBaudRate;
            }
            set
            {
                commandBaudRate = value;
            }
        }


        public string StopBits
        {
            get
            {
                return stopBits;
            }
            set
            {
                stopBits = value;
            }
        }


        public string DataBits
        {
            get
            {
                return dataBits;
            }
            set
            {
                dataBits = value;
            }
        }

        public string Parity
        {
            get
            {
                return parity;
            }
            set
            {
                parity = value;
            }
        }

        public int InterframeTimeout
        {
            get
            {
                return interframeTimeout;
            }
            set
            {
                interframeTimeout = value;
            }
        }


        public int ServerSAP
        {
            get
            {
                return serverSAP;
            }
            set
            {
                serverSAP = value;
            }
        }


        public int ServerLowerMacAddress
        {
            get
            {
                return serverLowerMacAddress;
            }
            set
            {
                serverLowerMacAddress = value;
            }
        }


        public byte ApplicationContext
        {
            get
            {
                return applicationContext;
            }
            set
            {
                applicationContext = value;
            }
        }


        public int PDUSize
        {
            get
            {
                return pduSize;
            }
            set
            {
                pduSize = value;
            }
        }

        public byte Cnf1
        {
            get
            {
                return cnf1;
            }
            set
            {
                cnf1 = value;
            }
        }


        public byte Cnf2
        {
            get
            {
                return cnf2;
            }
            set
            {
                cnf2 = value;
            }
        }


        public byte Cnf3
        {
            get
            {
                return cnf3;
            }
            set
            {
                cnf3 = value;
            }
        }


        public string ReadOut
        {
            get
            {
                return readOut;
            }
            set
            {
                readOut = value;
            }
        }


        public string Billing
        {
            get
            {
                return billing;
            }
            set
            {
                billing = value;
            }
        }


        public string BillingVZ
        {
            get
            {
                return billingVZ;
            }
            set
            {
                billingVZ = value;
            }
        }


        public string TamperXML
        {
            get
            {
                return tamperXML;
            }
            set
            {
                tamperXML = value;
            }
        }


        public string CommunicationPort
        {
            get
            {
                return communicationPort;
            }
            set
            {
                communicationPort = value;
            }
        }


        public string CommunicationMode
        {
            get
            {
                return communicationMode;
            }
            set
            {
                communicationMode = value;
            }
        }

        public string ModemNumber
        {
            get
            {
                return modemNumber;
            }
            set
            {
                modemNumber = value;
            }
        }


        public string ScaleXMLPath
        {
            get
            {
                return scaleXMLPath;
            }
            set
            {
                scaleXMLPath = value;
            }
        }


        public string HLSKey
        {
            get
            {
                return hlsKey;
            }
            set
            {
                hlsKey = value;
            }
        }


        public int ClientSAP
        {
            get
            {
                return clientSAP;
            }
            set
            {
                clientSAP = value;
            }
        }


        public int CommandTimeOut
        {
            get
            {
                return commandTimeOut;
            }
            set
            {
                commandTimeOut = value;
            }
        }

        public int IntercharacterDelay
        {
            get
            {
                return intercharacterDelay;
            }
            set
            {
                intercharacterDelay = value;
            }
        }

        public byte SecurityMechanism
        {
            get
            {
                return securityMechanism;
            }
            set
            {
                securityMechanism = value;
            }
        }


        public string Password
        {
            get
            {
                return password;
            }
            set
            {
                password = value;
            }
        }
        /// <summary>
        /// Gets or sets the maximum load survey configured.
        /// </summary>
        public int MaxLoadSurveyDays
        {
            get
            {
                return maxLoadSurveyDays;
            }
            set
            {
                maxLoadSurveyDays = value;
            }
        }
    }
}
