//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandisGyr.AMI.Layers
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestOfbase64Binary", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class RequestOfbase64Binary : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] CommandField;
        
        private LandisGyr.AMI.Layers.DeviceInfo[] DevicesField;
        
        private string MessageIDField;
        
        private LandisGyr.AMI.Layers.SLAParameters SLAField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Command
        {
            get
            {
                return this.CommandField;
            }
            set
            {
                this.CommandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.DeviceInfo[] Devices
        {
            get
            {
                return this.DevicesField;
            }
            set
            {
                this.DevicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageID
        {
            get
            {
                return this.MessageIDField;
            }
            set
            {
                this.MessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.SLAParameters SLA
        {
            get
            {
                return this.SLAField;
            }
            set
            {
                this.SLAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SLAParameters", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class SLAParameters : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PriorityField;
        
        private int RetryCountField;
        
        private LandisGyr.AMI.Layers.RetryAlgorithm RetryIntervalAlgorithmField;
        
        private LandisGyr.AMI.Layers.SecurityAttributes SecurityField;
        
        private System.Nullable<System.DateTime> TimeToLiveField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RetryCount
        {
            get
            {
                return this.RetryCountField;
            }
            set
            {
                this.RetryCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.RetryAlgorithm RetryIntervalAlgorithm
        {
            get
            {
                return this.RetryIntervalAlgorithmField;
            }
            set
            {
                this.RetryIntervalAlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.SecurityAttributes Security
        {
            get
            {
                return this.SecurityField;
            }
            set
            {
                this.SecurityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeToLive
        {
            get
            {
                return this.TimeToLiveField;
            }
            set
            {
                this.TimeToLiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceInfo", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class DeviceInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SerialNumberField;
        
        private LandisGyr.AMI.Layers.SessionDetails SessionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber
        {
            get
            {
                return this.SerialNumberField;
            }
            set
            {
                this.SerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.SessionDetails Session
        {
            get
            {
                return this.SessionField;
            }
            set
            {
                this.SessionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionDetails", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class SessionDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private LandisGyr.AMI.Layers.SessionMode ModeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.SessionMode Mode
        {
            get
            {
                return this.ModeField;
            }
            set
            {
                this.ModeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionMode", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public enum SessionMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseExistingOrNo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UseExistingOrNew = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CloseAfterResponse = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Close = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityAttributes", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class SecurityAttributes : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool EncryptMessageField;
        
        private bool SignMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EncryptMessage
        {
            get
            {
                return this.EncryptMessageField;
            }
            set
            {
                this.EncryptMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SignMessage
        {
            get
            {
                return this.SignMessageField;
            }
            set
            {
                this.SignMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetryAlgorithm", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public enum RetryAlgorithm : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegularInterval = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncrementalTimeInterval = 1,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://LandisGyr.AMI.Network/Common", ConfigurationName="INetworkProtocol")]
public interface INetworkProtocol
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://LandisGyr.AMI.Network/Common/INetworkProtocol/Send", ReplyAction="http://LandisGyr.AMI.Network/Common/INetworkProtocol/SendResponse")]
    void Send(LandisGyr.AMI.Layers.RequestOfbase64Binary[] requests);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://LandisGyr.AMI.Network/Common/INetworkProtocol/CloseSession", ReplyAction="http://LandisGyr.AMI.Network/Common/INetworkProtocol/CloseSessionResponse")]
    void CloseSession(string[] arrayOfSessionID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface INetworkProtocolChannel : INetworkProtocol, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class NetworkProtocolClient : System.ServiceModel.ClientBase<INetworkProtocol>, INetworkProtocol
{
    
    public NetworkProtocolClient()
    {
    }
    
    public NetworkProtocolClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NetworkProtocolClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NetworkProtocolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NetworkProtocolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Send(LandisGyr.AMI.Layers.RequestOfbase64Binary[] requests)
    {
        base.Channel.Send(requests);
    }
    
    public void CloseSession(string[] arrayOfSessionID)
    {
        base.Channel.CloseSession(arrayOfSessionID);
    }
}
