//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastDownloading {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FDLOperationsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FDLOperationsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastDownloading.FDLOperationsResource", typeof(FDLOperationsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomaly data read out in progress....
        /// </summary>
        internal static string AnomalyDataReadingInprogress {
            get {
                return ResourceManager.GetString("AnomalyDataReadingInprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing data parsed successfully..
        /// </summary>
        internal static string BillingDataParsed {
            get {
                return ResourceManager.GetString("BillingDataParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing data read out in progress....
        /// </summary>
        internal static string BillingDataReadingInprogress {
            get {
                return ResourceManager.GetString("BillingDataReadingInprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General data read out in progress....
        /// </summary>
        internal static string GeneralReadingInprogress {
            get {
                return ResourceManager.GetString("GeneralReadingInprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant data read out in progress....
        /// </summary>
        internal static string InstantDataReadingInprogress {
            get {
                return ResourceManager.GetString("InstantDataReadingInprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load survey data parsed successfully..
        /// </summary>
        internal static string LSDataParsed {
            get {
                return ResourceManager.GetString("LSDataParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete load survey data read out in progress....
        /// </summary>
        internal static string LSDataReadingInprogress {
            get {
                return ResourceManager.GetString("LSDataReadingInprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid night data read out in progress....
        /// </summary>
        internal static string MidNightDataReadingInprogress {
            get {
                return ResourceManager.GetString("MidNightDataReadingInprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Billing Data.
        /// </summary>
        internal static string ParsingBillingData {
            get {
                return ResourceManager.GetString("ParsingBillingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading General Data.
        /// </summary>
        internal static string ParsingGeneralData {
            get {
                return ResourceManager.GetString("ParsingGeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Instantaneous Data.
        /// </summary>
        internal static string ParsingInstantData {
            get {
                return ResourceManager.GetString("ParsingInstantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Load Survey Data.
        /// </summary>
        internal static string ParsingLSData {
            get {
                return ResourceManager.GetString("ParsingLSData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Tamper Data.
        /// </summary>
        internal static string ParsingTamperData {
            get {
                return ResourceManager.GetString("ParsingTamperData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasor data read out in progress....
        /// </summary>
        internal static string PhasorDataReadingInprogress {
            get {
                return ResourceManager.GetString("PhasorDataReadingInprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamper data parsed successfully..
        /// </summary>
        internal static string TamperDataParsed {
            get {
                return ResourceManager.GetString("TamperDataParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamper data read out in progress....
        /// </summary>
        internal static string TamperDataReadingInprogress {
            get {
                return ResourceManager.GetString("TamperDataReadingInprogress", resourceCulture);
            }
        }
    }
}
