//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace CAB.Framework
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ModemConfig
    {

        private ModemConfigProperties[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModemName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModemConfigProperties[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModemConfigProperties
    {

        private string typeofconnectionField;

        private ModemConfigModemNamePortsettings[] portsettingsField;

        private ModemConfigModemNameCommandsettings[] commandsettingsField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Typeofconnection
        {
            get
            {
                return this.typeofconnectionField;
            }
            set
            {
                this.typeofconnectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portsettings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModemConfigModemNamePortsettings[] Portsettings
        {
            get
            {
                return this.portsettingsField;
            }
            set
            {
                this.portsettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Commandsettings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ModemConfigModemNameCommandsettings[] Commandsettings
        {
            get
            {
                return this.commandsettingsField;
            }
            set
            {
                this.commandsettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModemConfigModemNamePortsettings
    {

        private string bitsPerSecondField;

        private string databitsField;

        private string parityField;

        private string stopbitsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BitsPerSecond
        {
            get
            {
                return this.bitsPerSecondField;
            }
            set
            {
                this.bitsPerSecondField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Databits
        {
            get
            {
                return this.databitsField;
            }
            set
            {
                this.databitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Parity
        {
            get
            {
                return this.parityField;
            }
            set
            {
                this.parityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stopbits
        {
            get
            {
                return this.stopbitsField;
            }
            set
            {
                this.stopbitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ModemConfigModemNameCommandsettings
    {

        private string dialField;

        private string initializeField;

        private string resetField;

        private string initializeBaudRateField;

        private string initializeSettingsField;

        private string resetBaudRateField;

        private string resetSettingsField;

        private string reConnect;

        private bool isReConnect;

        private int commandTimeout;

        private int interCharacterTimeout;

        //For storing dlms retries
        private int dLMSRetries;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dial
        {
            get
            {
                return this.dialField;
            }
            set
            {
                this.dialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Initialize
        {
            get
            {
                return this.initializeField;
            }
            set
            {
                this.initializeField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReConnect
        {
            get
            {
                return this.reConnect;
            }
            set
            {
                this.reConnect = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsReConnect
        {
            get
            {
                return this.isReConnect;
            }
            set
            {
                this.isReConnect = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reset
        {
            get
            {
                return this.resetField;
            }
            set
            {
                this.resetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InitializeBaudRate
        {
            get
            {
                return this.initializeBaudRateField;
            }
            set
            {
                this.initializeBaudRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InitializeSettings
        {
            get
            {
                return this.initializeSettingsField;
            }
            set
            {
                this.initializeSettingsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResetBaudRate
        {
            get
            {
                return this.resetBaudRateField;
            }
            set
            {
                this.resetBaudRateField = value;
            }
        }
        /// <summary>
        /// For holding DLMS Retries
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DLMSRetries
        {
            get
            {
                return this.dLMSRetries;
            }
            set
            {
                this.dLMSRetries = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResetSettings
        {
            get
            {
                return this.resetSettingsField;
            }
            set
            {
                this.resetSettingsField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CommandTimeout
        {
            get
            {
                return this.commandTimeout;
            }
            set
            {
                this.commandTimeout = value;
            }
        }
        public int InterCharacterTimeout
        {
           get
           {
              return this.interCharacterTimeout;
           }
            set
            {
                this.interCharacterTimeout = value;
            }
        }
    }
}
