//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CABApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutEdge {
            get {
                object obj = ResourceManager.GetObject("AboutEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^a-zA-Z0-9.{\\s}].
        /// </summary>
        internal static string ALPHANUMERICCHARREGEX {
            get {
                return ResourceManager.GetString("ALPHANUMERICCHARREGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^a-zA-Z0-9].
        /// </summary>
        internal static string ALPHANUMERICREGEX {
            get {
                return ResourceManager.GetString("ALPHANUMERICREGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bakgroundmain {
            get {
                object obj = ResourceManager.GetObject("bakgroundmain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCS.
        /// </summary>
        internal static string BCS {
            get {
                return ResourceManager.GetString("BCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        internal static string CCPrivateKey {
            get {
                return ResourceManager.GetString("CCPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CMRI_Communication {
            get {
                object obj = ResourceManager.GetObject("CMRI Communication", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Consumer_Meter_Definition {
            get {
                object obj = ResourceManager.GetObject("Consumer_Meter_Definition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days remaining in demo trial version.
        /// </summary>
        internal static string DAYSREMAINING {
            get {
                return ResourceManager.GetString("DAYSREMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}.
        /// </summary>
        internal static string DAYSREMAININGFORMATSTR {
            get {
                return ResourceManager.GetString("DAYSREMAININGFORMATSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIM2ndEditionService.
        /// </summary>
        internal static string EndPointConfigurationName {
            get {
                return ResourceManager.GetString("EndPointConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons {
            get {
                object obj = ResourceManager.GetObject("Icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Key!.
        /// </summary>
        internal static string INVALIDKEY {
            get {
                return ResourceManager.GetString("INVALIDKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^a-zA-Z0-9].
        /// </summary>
        internal static string ISALPHANUMERIC {
            get {
                return ResourceManager.GetString("ISALPHANUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^a-zA-Z0-9.{\\s}].
        /// </summary>
        internal static string ISALPHANUMERICCHAR {
            get {
                return ResourceManager.GetString("ISALPHANUMERICCHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key Cannot Be Blank.
        /// </summary>
        internal static string KEYCANNOTBEBLANK {
            get {
                return ResourceManager.GetString("KEYCANNOTBEBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License files (*.LCS)|*.LCS.
        /// </summary>
        internal static string LCSFILEFILTER {
            get {
                return ResourceManager.GetString("LCSFILEFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Local_Meter_Communication {
            get {
                object obj = ResourceManager.GetObject("Local Meter Communication", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://indelvr374.ap.bm.net/GSIS_CIM2ndEdition/CIM2ndEd.svc.
        /// </summary>
        internal static string RemoteAddress {
            get {
                return ResourceManager.GetString("RemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the program as an administrator!.
        /// </summary>
        internal static string RUNASADMIN {
            get {
                return ResourceManager.GetString("RUNASADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a group to delete !..
        /// </summary>
        internal static string SELECTAGROUPTODELETE {
            get {
                return ResourceManager.GetString("SELECTAGROUPTODELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Product Key Send This File To Your Vender !.
        /// </summary>
        internal static string SENDFILETOVENDOR {
            get {
                return ResourceManager.GetString("SENDFILETOVENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic3PhaseCommunication.
        /// </summary>
        internal static string SERVICENAME {
            get {
                return ResourceManager.GetString("SERVICENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login service is not available on your system.Please contact your administrator..
        /// </summary>
        internal static string SERVICENOTEXISTS {
            get {
                return ResourceManager.GetString("SERVICENOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap System_Configuration_Settings {
            get {
                object obj = ResourceManager.GetObject("System Configuration Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton5 {
            get {
                object obj = ResourceManager.GetObject("toolStripButton5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Trial Expired.
        /// </summary>
        internal static string TRIALEXPIRED {
            get {
                return ResourceManager.GetString("TRIALEXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserInfo {
            get {
                object obj = ResourceManager.GetObject("UserInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
