//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLMS_Final.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UtilityMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilityMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLMS_Final.Utility.UtilityMessage", typeof(UtilityMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.Please change the mode.
        /// </summary>
        internal static string ACCESSDENIEDPLSCHANGEMODE {
            get {
                return ResourceManager.GetString("ACCESSDENIEDPLSCHANGEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value for meter id..
        /// </summary>
        internal static string BlankMeterID {
            get {
                return ResourceManager.GetString("BlankMeterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size is insufficent..
        /// </summary>
        internal static string BufferSizeInsufficent {
            get {
                return ResourceManager.GetString("BufferSizeInsufficent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFC File created successfully..
        /// </summary>
        internal static string CFCCREATESUCCESS {
            get {
                return ResourceManager.GetString("CFCCREATESUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFC File is not correct.
        /// </summary>
        internal static string CFCFILENOTCORRECT {
            get {
                return ResourceManager.GetString("CFCFILENOTCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFC File is uploaded successfully.
        /// </summary>
        internal static string CFCUPLOADSUCCESS {
            get {
                return ResourceManager.GetString("CFCUPLOADSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRI Connection Failed..
        /// </summary>
        internal static string CMRICONNECTIONFAILED {
            get {
                return ResourceManager.GetString("CMRICONNECTIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Successfully completed for all meter IDs from CMRI and Saved in.
        /// </summary>
        internal static string CMRISucessMessage {
            get {
                return ResourceManager.GetString("CMRISucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRI view cant not be null..
        /// </summary>
        internal static string CMRIViewCanNotBeNull {
            get {
                return ResourceManager.GetString("CMRIViewCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate Fast download command file..
        /// </summary>
        internal static string CommandFileNotFound {
            get {
                return ResourceManager.GetString("CommandFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosem Connection Failed..
        /// </summary>
        internal static string CosemConnectionFailed {
            get {
                return ResourceManager.GetString("CosemConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT.
        /// </summary>
        internal static string CT {
            get {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Corrupt in CMRI please contact your Administrator..
        /// </summary>
        internal static string DataCorruptInCMRI {
            get {
                return ResourceManager.GetString("DataCorruptInCMRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data read out from meter complted..
        /// </summary>
        internal static string DataReadoutEnd {
            get {
                return ResourceManager.GetString("DataReadoutEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data read out from meter started..
        /// </summary>
        internal static string DataReadoutStarted {
            get {
                return ResourceManager.GetString("DataReadoutStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is successfully saved in .
        /// </summary>
        internal static string DataSaveIn {
            get {
                return ResourceManager.GetString("DataSaveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00:00.
        /// </summary>
        internal static string DefaultDurationValue {
            get {
                return ResourceManager.GetString("DefaultDurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLMS connection not available..
        /// </summary>
        internal static string DLMSCONNECTIONNOTAVAILABLE {
            get {
                return ResourceManager.GetString("DLMSCONNECTIONNOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (hh:mm:ss) .
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failed with meter..
        /// </summary>
        internal static string ErrorInCommunication {
            get {
                return ResourceManager.GetString("ErrorInCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Display Error.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in Accuracy Check Read Out.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating file..
        /// </summary>
        internal static string FileCreationError {
            get {
                return ResourceManager.GetString("FileCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name cannot be null..
        /// </summary>
        internal static string FileNameCanNotBeNull {
            get {
                return ResourceManager.GetString("FileNameCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First TOU table can not be left blank..
        /// </summary>
        internal static string FIRSTTOUCANNOTBEBLANK {
            get {
                return ResourceManager.GetString("FIRSTTOUCANNOTBEBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Tou Actvation date must not be 29 feb..
        /// </summary>
        internal static string FUTURETOUACTIVATEDATENOTBE29FEB {
            get {
                return ResourceManager.GetString("FUTURETOUACTIVATEDATENOTBE29FEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General/Instant data readout complete..
        /// </summary>
        internal static string GeneralInstantaDataReadoutcompleted {
            get {
                return ResourceManager.GetString("GeneralInstantaDataReadoutcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDLC Connection Failed..
        /// </summary>
        internal static string HDLCConnectionFailed {
            get {
                return ResourceManager.GetString("HDLCConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid meter id..
        /// </summary>
        internal static string IncorrectMeterID {
            get {
                return ResourceManager.GetString("IncorrectMeterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size is insufficient to download data. Please reconfigure it..
        /// </summary>
        internal static string InsufficientBufferSize {
            get {
                return ResourceManager.GetString("InsufficientBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string INVALID {
            get {
                return ResourceManager.GetString("INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Response bytes..
        /// </summary>
        internal static string InvalidResponse {
            get {
                return ResourceManager.GetString("InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        internal static string NoDataToSave {
            get {
                return ResourceManager.GetString("NoDataToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more enteries allowed as the day is complete.
        /// </summary>
        internal static string NOMOREENTERIESALLOWEDTHEDAYISCOMPLETE {
            get {
                return ResourceManager.GetString("NOMOREENTERIESALLOWEDTHEDAYISCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to disconnect.Please try again..
        /// </summary>
        internal static string NotableToDisconnect {
            get {
                return ResourceManager.GetString("NotableToDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter written successfully..
        /// </summary>
        internal static string PARAMETERWRITEENSUCESSFULLY {
            get {
                return ResourceManager.GetString("PARAMETERWRITEENSUCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied..
        /// </summary>
        internal static string Permissiondenied {
            get {
                return ResourceManager.GetString("Permissiondenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General/Instant data reading in progress... .
        /// </summary>
        internal static string ReadingGeneralInstantData {
            get {
                return ResourceManager.GetString("ReadingGeneralInstantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving downloaded data to file.
        /// </summary>
        internal static string SavingDataToFile {
            get {
                return ResourceManager.GetString("SavingDataToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season slot not complete..
        /// </summary>
        internal static string SEASONSLOTCANNOTBEBLANK {
            get {
                return ResourceManager.GetString("SEASONSLOTCANNOTBEBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option to download data..
        /// </summary>
        internal static string Selectanoption {
            get {
                return ResourceManager.GetString("Selectanoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Billing Parameters..
        /// </summary>
        internal static string SELECTBILLINGPARAMETERS {
            get {
                return ResourceManager.GetString("SELECTBILLINGPARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to read..
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Integration Period..
        /// </summary>
        internal static string SELECTINTEGRATIONPERIOD {
            get {
                return ResourceManager.GetString("SELECTINTEGRATIONPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Load Survey Capture Period..
        /// </summary>
        internal static string SELECTLSCAPTUREPERIOD {
            get {
                return ResourceManager.GetString("SELECTLSCAPTUREPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option to read..
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option to read..
        /// </summary>
        internal static string SelectReadoption {
            get {
                return ResourceManager.GetString("SelectReadoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter accuracy check is running, Do you want to close  window?.
        /// </summary>
        internal static string TestRunning {
            get {
                return ResourceManager.GetString("TestRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOD Table grid(s) cannot be null.
        /// </summary>
        internal static string TODDAYTABLEGRIDCANNOTBENULL {
            get {
                return ResourceManager.GetString("TODDAYTABLEGRIDCANNOTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill TOD Detail..
        /// </summary>
        internal static string TODTABLECANNOTBEBLANK {
            get {
                return ResourceManager.GetString("TODTABLECANNOTBEBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU Activation grid cannot be null..
        /// </summary>
        internal static string TOUACTIVATIONGRIDCANNOTBENULL {
            get {
                return ResourceManager.GetString("TOUACTIVATIONGRIDCANNOTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill TOU Day table..
        /// </summary>
        internal static string TOUDAYTABLECANNOTBEBLANK {
            get {
                return ResourceManager.GetString("TOUDAYTABLECANNOTBEBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU DayTable grid cannot be null.
        /// </summary>
        internal static string TOUDAYTABLEGRIDCANNOTBENULL {
            get {
                return ResourceManager.GetString("TOUDAYTABLEGRIDCANNOTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU Grids cannot be null..
        /// </summary>
        internal static string TOUGRIDSCANNOTBENULL {
            get {
                return ResourceManager.GetString("TOUGRIDSCANNOTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill TOU Season table..
        /// </summary>
        internal static string TOUSEASONTABLECANNOTBEBLANK {
            get {
                return ResourceManager.GetString("TOUSEASONTABLECANNOTBEBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill TOU table..
        /// </summary>
        internal static string TOUTABLENOTCOMPLETE {
            get {
                return ResourceManager.GetString("TOUTABLENOTCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU View cannot be null..
        /// </summary>
        internal static string TOUVIEWCANNOTBENULL {
            get {
                return ResourceManager.GetString("TOUVIEWCANNOTBENULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill TOU Week table..
        /// </summary>
        internal static string TOUWEEKTABLECANNOTBEBLANK {
            get {
                return ResourceManager.GetString("TOUWEEKTABLECANNOTBEBLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read commands from command file.
        /// </summary>
        internal static string UnableToReadCommandFile {
            get {
                return ResourceManager.GetString("UnableToReadCommandFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.000000.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
