//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandisGyr.AMI.Layers
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endpoint", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class Endpoint : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LandisGyr.AMI.Layers.Meter[] AssociatedMetersField;
        
        private byte[] ConfigurationField;
        
        private string FirmwareVersionField;
        
        private bool IsUsableField;
        
        private LandisGyr.AMI.Layers.EndpointModel ModelField;
        
        private string SerialNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.Meter[] AssociatedMeters
        {
            get
            {
                return this.AssociatedMetersField;
            }
            set
            {
                this.AssociatedMetersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Configuration
        {
            get
            {
                return this.ConfigurationField;
            }
            set
            {
                this.ConfigurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmwareVersion
        {
            get
            {
                return this.FirmwareVersionField;
            }
            set
            {
                this.FirmwareVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUsable
        {
            get
            {
                return this.IsUsableField;
            }
            set
            {
                this.IsUsableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.EndpointModel Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber
        {
            get
            {
                return this.SerialNumberField;
            }
            set
            {
                this.SerialNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointModel", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class EndpointModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private LandisGyr.AMI.Layers.EndpointType TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.EndpointType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meter", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class Meter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] ConfigurationField;
        
        private string FirmwareVersionField;
        
        private string MeterNumberField;
        
        private LandisGyr.AMI.Layers.MeterModel ModelField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Configuration
        {
            get
            {
                return this.ConfigurationField;
            }
            set
            {
                this.ConfigurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmwareVersion
        {
            get
            {
                return this.FirmwareVersionField;
            }
            set
            {
                this.FirmwareVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.MeterModel Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterModel", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public partial class MeterModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private LandisGyr.AMI.Layers.MeterType TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LandisGyr.AMI.Layers.MeterType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterType", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public enum MeterType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Electric = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gas = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Water = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndpointType", Namespace="http://schemas.datacontract.org/2004/07/LandisGyr.AMI.Layers")]
    public enum EndpointType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GSRF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GPRS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://LandisGyr.AMI.Layers/Common", ConfigurationName="IEndpointOperations")]
public interface IEndpointOperations
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/AddEndpoints", ReplyAction="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/AddEndpointsResponse")]
    void AddEndpoints(LandisGyr.AMI.Layers.Endpoint[] newEndpoints);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/UpdateEndpoints", ReplyAction="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/UpdateEndpointsResponse")]
    void UpdateEndpoints(LandisGyr.AMI.Layers.Endpoint[] endpoints);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/RemoveEndpoints", ReplyAction="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/RemoveEndpointsResponse")]
    void RemoveEndpoints(LandisGyr.AMI.Layers.Endpoint[] endpoints);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/EndpointStateChangeEvent", ReplyAction="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/EndpointStateChangeEventRe" +
        "sponse")]
    void EndpointStateChangeEvent(LandisGyr.AMI.Layers.Endpoint[] endpoints);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/ConfigurationChangeEvent", ReplyAction="http://LandisGyr.AMI.Layers/Common/IEndpointOperations/ConfigurationChangeEventRe" +
        "sponse")]
    void ConfigurationChangeEvent(LandisGyr.AMI.Layers.Endpoint[] endpoints);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IEndpointOperationsChannel : IEndpointOperations, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class EndpointOperationsClient : System.ServiceModel.ClientBase<IEndpointOperations>, IEndpointOperations
{
    
    public EndpointOperationsClient()
    {
    }
    
    public EndpointOperationsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EndpointOperationsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EndpointOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EndpointOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddEndpoints(LandisGyr.AMI.Layers.Endpoint[] newEndpoints)
    {
        base.Channel.AddEndpoints(newEndpoints);
    }
    
    public void UpdateEndpoints(LandisGyr.AMI.Layers.Endpoint[] endpoints)
    {
        base.Channel.UpdateEndpoints(endpoints);
    }
    
    public void RemoveEndpoints(LandisGyr.AMI.Layers.Endpoint[] endpoints)
    {
        base.Channel.RemoveEndpoints(endpoints);
    }
    
    public void EndpointStateChangeEvent(LandisGyr.AMI.Layers.Endpoint[] endpoints)
    {
        base.Channel.EndpointStateChangeEvent(endpoints);
    }
    
    public void ConfigurationChangeEvent(LandisGyr.AMI.Layers.Endpoint[] endpoints)
    {
        base.Channel.ConfigurationChangeEvent(endpoints);
    }
}
