//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEC.CAB.AppControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IEC.CAB.AppControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Login.
        /// </summary>
        internal static string B000001 {
            get {
                return ResourceManager.GetString("B000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string B000002 {
            get {
                return ResourceManager.GetString("B000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string B000003 {
            get {
                return ResourceManager.GetString("B000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string B000004 {
            get {
                return ResourceManager.GetString("B000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string B000005 {
            get {
                return ResourceManager.GetString("B000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        internal static string B000006 {
            get {
                return ResourceManager.GetString("B000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find Now.
        /// </summary>
        internal static string B000007 {
            get {
                return ResourceManager.GetString("B000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string B000008 {
            get {
                return ResourceManager.GetString("B000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string B000009 {
            get {
                return ResourceManager.GetString("B000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &amp;New Meter Details.
        /// </summary>
        internal static string B000010 {
            get {
                return ResourceManager.GetString("B000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        internal static string B000011 {
            get {
                return ResourceManager.GetString("B000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upload.
        /// </summary>
        internal static string B000012 {
            get {
                return ResourceManager.GetString("B000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pick.
        /// </summary>
        internal static string B000013 {
            get {
                return ResourceManager.GetString("B000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string B000014 {
            get {
                return ResourceManager.GetString("B000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare CMRI.
        /// </summary>
        internal static string B000015 {
            get {
                return ResourceManager.GetString("B000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Data.
        /// </summary>
        internal static string B000016 {
            get {
                return ResourceManager.GetString("B000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update RTC.
        /// </summary>
        internal static string B000017 {
            get {
                return ResourceManager.GetString("B000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import.
        /// </summary>
        internal static string B000018 {
            get {
                return ResourceManager.GetString("B000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lear CMRI.
        /// </summary>
        internal static string B000019 {
            get {
                return ResourceManager.GetString("B000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        internal static string B000020 {
            get {
                return ResourceManager.GetString("B000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string C000001 {
            get {
                return ResourceManager.GetString("C000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string C000002 {
            get {
                return ResourceManager.GetString("C000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string C000003 {
            get {
                return ResourceManager.GetString("C000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect with Database server. Please contact system administrator..
        /// </summary>
        internal static string D000001 {
            get {
                return ResourceManager.GetString("D000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Id.
        /// </summary>
        internal static string L000001 {
            get {
                return ResourceManager.GetString("L000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string L000002 {
            get {
                return ResourceManager.GetString("L000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Type.
        /// </summary>
        internal static string L000003 {
            get {
                return ResourceManager.GetString("L000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string L000004 {
            get {
                return ResourceManager.GetString("L000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ID.
        /// </summary>
        internal static string L000005 {
            get {
                return ResourceManager.GetString("L000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string L000006 {
            get {
                return ResourceManager.GetString("L000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string L000007 {
            get {
                return ResourceManager.GetString("L000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string L000008 {
            get {
                return ResourceManager.GetString("L000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note  :  Strict ( * ) marked field is mandatory to enter..
        /// </summary>
        internal static string L000009 {
            get {
                return ResourceManager.GetString("L000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string L000010 {
            get {
                return ResourceManager.GetString("L000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string L000011 {
            get {
                return ResourceManager.GetString("L000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRI Number.
        /// </summary>
        internal static string L000012 {
            get {
                return ResourceManager.GetString("L000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRI Description.
        /// </summary>
        internal static string L000013 {
            get {
                return ResourceManager.GetString("L000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer ID.
        /// </summary>
        internal static string L000014 {
            get {
                return ResourceManager.GetString("L000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Name.
        /// </summary>
        internal static string L000015 {
            get {
                return ResourceManager.GetString("L000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Type.
        /// </summary>
        internal static string L000016 {
            get {
                return ResourceManager.GetString("L000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        internal static string L000017 {
            get {
                return ResourceManager.GetString("L000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Number.
        /// </summary>
        internal static string L000018 {
            get {
                return ResourceManager.GetString("L000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string L000019 {
            get {
                return ResourceManager.GetString("L000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Town.
        /// </summary>
        internal static string L000020 {
            get {
                return ResourceManager.GetString("L000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string L000021 {
            get {
                return ResourceManager.GetString("L000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Number.
        /// </summary>
        internal static string L000022 {
            get {
                return ResourceManager.GetString("L000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Type.
        /// </summary>
        internal static string L000023 {
            get {
                return ResourceManager.GetString("L000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Model.
        /// </summary>
        internal static string L000024 {
            get {
                return ResourceManager.GetString("L000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string L000025 {
            get {
                return ResourceManager.GetString("L000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Date.
        /// </summary>
        internal static string L000026 {
            get {
                return ResourceManager.GetString("L000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMF.
        /// </summary>
        internal static string L000027 {
            get {
                return ResourceManager.GetString("L000027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Demand.
        /// </summary>
        internal static string L000028 {
            get {
                return ResourceManager.GetString("L000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter CT/PT.
        /// </summary>
        internal static string L000029 {
            get {
                return ResourceManager.GetString("L000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT Primary (Amp).
        /// </summary>
        internal static string L000030 {
            get {
                return ResourceManager.GetString("L000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT Secondary (Amp).
        /// </summary>
        internal static string L000031 {
            get {
                return ResourceManager.GetString("L000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT Ratio.
        /// </summary>
        internal static string L000032 {
            get {
                return ResourceManager.GetString("L000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT Primary (V).
        /// </summary>
        internal static string L000033 {
            get {
                return ResourceManager.GetString("L000033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT Secondary (V).
        /// </summary>
        internal static string L000034 {
            get {
                return ResourceManager.GetString("L000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT Ratio.
        /// </summary>
        internal static string L000035 {
            get {
                return ResourceManager.GetString("L000035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed .
        /// </summary>
        internal static string L000036 {
            get {
                return ResourceManager.GetString("L000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Meter.
        /// </summary>
        internal static string L000037 {
            get {
                return ResourceManager.GetString("L000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string L000038 {
            get {
                return ResourceManager.GetString("L000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string L000039 {
            get {
                return ResourceManager.GetString("L000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indicates optional fields.
        /// </summary>
        internal static string L000040 {
            get {
                return ResourceManager.GetString("L000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        internal static string L000041 {
            get {
                return ResourceManager.GetString("L000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Name.
        /// </summary>
        internal static string L000042 {
            get {
                return ResourceManager.GetString("L000042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Name.
        /// </summary>
        internal static string L000043 {
            get {
                return ResourceManager.GetString("L000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Selection.
        /// </summary>
        internal static string L000044 {
            get {
                return ResourceManager.GetString("L000044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRI Selection.
        /// </summary>
        internal static string L000045 {
            get {
                return ResourceManager.GetString("L000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMRI.
        /// </summary>
        internal static string L000046 {
            get {
                return ResourceManager.GetString("L000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Meter.
        /// </summary>
        internal static string L000047 {
            get {
                return ResourceManager.GetString("L000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Meter.
        /// </summary>
        internal static string L000048 {
            get {
                return ResourceManager.GetString("L000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string L000049 {
            get {
                return ResourceManager.GetString("L000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Name.
        /// </summary>
        internal static string L000050 {
            get {
                return ResourceManager.GetString("L000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        internal static string L000051 {
            get {
                return ResourceManager.GetString("L000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Type.
        /// </summary>
        internal static string L000052 {
            get {
                return ResourceManager.GetString("L000052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Type.
        /// </summary>
        internal static string L000053 {
            get {
                return ResourceManager.GetString("L000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string L000054 {
            get {
                return ResourceManager.GetString("L000054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string L000055 {
            get {
                return ResourceManager.GetString("L000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Group Name.
        /// </summary>
        internal static string L000056 {
            get {
                return ResourceManager.GetString("L000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string L000057 {
            get {
                return ResourceManager.GetString("L000057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Number.
        /// </summary>
        internal static string L000058 {
            get {
                return ResourceManager.GetString("L000058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be left blank.
        /// </summary>
        internal static string M000001 {
            get {
                return ResourceManager.GetString("M000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed. Please check the Login Id and Password.
        /// </summary>
        internal static string M000002 {
            get {
                return ResourceManager.GetString("M000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date should be less than To Date.
        /// </summary>
        internal static string M000003 {
            get {
                return ResourceManager.GetString("M000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . It can accept Characters, Numbers from 1 to 9 and Special Characters [!, $, #, @].
        /// </summary>
        internal static string M000004 {
            get {
                return ResourceManager.GetString("M000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password does not match.
        /// </summary>
        internal static string M000005 {
            get {
                return ResourceManager.GetString("M000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . It can accept Characters and Space.
        /// </summary>
        internal static string M000006 {
            get {
                return ResourceManager.GetString("M000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string M000007 {
            get {
                return ResourceManager.GetString("M000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully..
        /// </summary>
        internal static string M000008 {
            get {
                return ResourceManager.GetString("M000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text can not be empty..
        /// </summary>
        internal static string M000009 {
            get {
                return ResourceManager.GetString("M000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Search. It can not accept any special character..
        /// </summary>
        internal static string M000010 {
            get {
                return ResourceManager.GetString("M000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists..
        /// </summary>
        internal static string M000011 {
            get {
                return ResourceManager.GetString("M000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  It can accept Characters and Numbers from 0-9.
        /// </summary>
        internal static string M000012 {
            get {
                return ResourceManager.GetString("M000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg: abcd@hotmail.com.
        /// </summary>
        internal static string M000013 {
            get {
                return ResourceManager.GetString("M000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . It can accept only Numbers from 1-9.
        /// </summary>
        internal static string M000014 {
            get {
                return ResourceManager.GetString("M000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . It can accept Characters, Numbers from 0 to 9 and Special Characters[#/,-].
        /// </summary>
        internal static string M000015 {
            get {
                return ResourceManager.GetString("M000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT Primary should be greater than CT Secondary.
        /// </summary>
        internal static string M000016 {
            get {
                return ResourceManager.GetString("M000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT Primary should be greater than PT Secondary.
        /// </summary>
        internal static string M000017 {
            get {
                return ResourceManager.GetString("M000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed CT Primary should be greater than Installed CT Secondary.
        /// </summary>
        internal static string M000018 {
            get {
                return ResourceManager.GetString("M000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed PT Primary should be greater than Installed PT Secondary.
        /// </summary>
        internal static string M000019 {
            get {
                return ResourceManager.GetString("M000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully..
        /// </summary>
        internal static string M000020 {
            get {
                return ResourceManager.GetString("M000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully..
        /// </summary>
        internal static string M000021 {
            get {
                return ResourceManager.GetString("M000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Master.
        /// </summary>
        internal static string M000022 {
            get {
                return ResourceManager.GetString("M000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name cannot be empty..
        /// </summary>
        internal static string M000023 {
            get {
                return ResourceManager.GetString("M000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Already Exist..
        /// </summary>
        internal static string M000024 {
            get {
                return ResourceManager.GetString("M000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the Record..
        /// </summary>
        internal static string M000025 {
            get {
                return ResourceManager.GetString("M000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Master.
        /// </summary>
        internal static string M000026 {
            get {
                return ResourceManager.GetString("M000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Name cannot be empty..
        /// </summary>
        internal static string M000027 {
            get {
                return ResourceManager.GetString("M000027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Already Exist..
        /// </summary>
        internal static string M000028 {
            get {
                return ResourceManager.GetString("M000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Master.
        /// </summary>
        internal static string M000029 {
            get {
                return ResourceManager.GetString("M000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Name cannot be empty..
        /// </summary>
        internal static string M000030 {
            get {
                return ResourceManager.GetString("M000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Already Exist..
        /// </summary>
        internal static string M000031 {
            get {
                return ResourceManager.GetString("M000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Master.
        /// </summary>
        internal static string M000032 {
            get {
                return ResourceManager.GetString("M000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already exist..
        /// </summary>
        internal static string M000033 {
            get {
                return ResourceManager.GetString("M000033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name can&apos;t be empty..
        /// </summary>
        internal static string M000034 {
            get {
                return ResourceManager.GetString("M000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Already exist..
        /// </summary>
        internal static string M000035 {
            get {
                return ResourceManager.GetString("M000035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation name can&apos;t be empty..
        /// </summary>
        internal static string M000036 {
            get {
                return ResourceManager.GetString("M000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Master.
        /// </summary>
        internal static string M000037 {
            get {
                return ResourceManager.GetString("M000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the COM port..
        /// </summary>
        internal static string M000038 {
            get {
                return ResourceManager.GetString("M000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response from meter..
        /// </summary>
        internal static string M000039 {
            get {
                return ResourceManager.GetString("M000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fail..
        /// </summary>
        internal static string M000040 {
            get {
                return ResourceManager.GetString("M000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out !.
        /// </summary>
        internal static string M000041 {
            get {
                return ResourceManager.GetString("M000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading General and Billing Data..
        /// </summary>
        internal static string M000042 {
            get {
                return ResourceManager.GetString("M000042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Bytes :.
        /// </summary>
        internal static string M000043 {
            get {
                return ResourceManager.GetString("M000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load survey date successfully read..
        /// </summary>
        internal static string M000044 {
            get {
                return ResourceManager.GetString("M000044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter File Name.
        /// </summary>
        internal static string M000045 {
            get {
                return ResourceManager.GetString("M000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to overwrite the file ?.
        /// </summary>
        internal static string M000046 {
            get {
                return ResourceManager.GetString("M000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name can&apos;t be empty..
        /// </summary>
        internal static string M000047 {
            get {
                return ResourceManager.GetString("M000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Saved Successfully..
        /// </summary>
        internal static string M000048 {
            get {
                return ResourceManager.GetString("M000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fail. Please check the Configuration Settings..
        /// </summary>
        internal static string M000049 {
            get {
                return ResourceManager.GetString("M000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading RTC updates..
        /// </summary>
        internal static string M000050 {
            get {
                return ResourceManager.GetString("M000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Transaction Data..
        /// </summary>
        internal static string M000051 {
            get {
                return ResourceManager.GetString("M000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading programming updates..
        /// </summary>
        internal static string M000052 {
            get {
                return ResourceManager.GetString("M000052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamper Log Readout Comp  :.
        /// </summary>
        internal static string M000053 {
            get {
                return ResourceManager.GetString("M000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Instant Phasor Data..
        /// </summary>
        internal static string M000054 {
            get {
                return ResourceManager.GetString("M000054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in reading Phasor Diagram..
        /// </summary>
        internal static string M000055 {
            get {
                return ResourceManager.GetString("M000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bcc.  Bcc is not matching..
        /// </summary>
        internal static string M000056 {
            get {
                return ResourceManager.GetString("M000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Phasor Data..
        /// </summary>
        internal static string M000057 {
            get {
                return ResourceManager.GetString("M000057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Survey Readout  Day :.
        /// </summary>
        internal static string M000058 {
            get {
                return ResourceManager.GetString("M000058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Carrier Or No Network Coverage..
        /// </summary>
        internal static string M000059 {
            get {
                return ResourceManager.GetString("M000059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in sending command to the port..
        /// </summary>
        internal static string M000060 {
            get {
                return ResourceManager.GetString("M000060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Tamper Data..
        /// </summary>
        internal static string M000061 {
            get {
                return ResourceManager.GetString("M000061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Load survey Data..
        /// </summary>
        internal static string M000062 {
            get {
                return ResourceManager.GetString("M000062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Fraud Energy Data..
        /// </summary>
        internal static string M000063 {
            get {
                return ResourceManager.GetString("M000063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Reserve Energy Data..
        /// </summary>
        internal static string M000064 {
            get {
                return ResourceManager.GetString("M000064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in reading Phasor Diagram..
        /// </summary>
        internal static string M000065 {
            get {
                return ResourceManager.GetString("M000065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Load survey Data..
        /// </summary>
        internal static string M000066 {
            get {
                return ResourceManager.GetString("M000066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Load survey Day..
        /// </summary>
        internal static string M000067 {
            get {
                return ResourceManager.GetString("M000067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Read successfully..
        /// </summary>
        internal static string M000068 {
            get {
                return ResourceManager.GetString("M000068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabcon.
        /// </summary>
        internal static string M000069 {
            get {
                return ResourceManager.GetString("M000069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment Number : .
        /// </summary>
        internal static string M000070 {
            get {
                return ResourceManager.GetString("M000070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login id already exist..
        /// </summary>
        internal static string M000071 {
            get {
                return ResourceManager.GetString("M000071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the user?.
        /// </summary>
        internal static string M000072 {
            get {
                return ResourceManager.GetString("M000072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete the logged user..
        /// </summary>
        internal static string M000073 {
            get {
                return ResourceManager.GetString("M000073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Type can&apos;t be empty..
        /// </summary>
        internal static string M000074 {
            get {
                return ResourceManager.GetString("M000074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Type already exist..
        /// </summary>
        internal static string M000075 {
            get {
                return ResourceManager.GetString("M000075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Type can&apos;t be empty..
        /// </summary>
        internal static string M000076 {
            get {
                return ResourceManager.GetString("M000076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Type already exist..
        /// </summary>
        internal static string M000077 {
            get {
                return ResourceManager.GetString("M000077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name can&apos;t be empty..
        /// </summary>
        internal static string M000078 {
            get {
                return ResourceManager.GetString("M000078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit already exist..
        /// </summary>
        internal static string M000079 {
            get {
                return ResourceManager.GetString("M000079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Master.
        /// </summary>
        internal static string M000080 {
            get {
                return ResourceManager.GetString("M000080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file from the list..
        /// </summary>
        internal static string M000081 {
            get {
                return ResourceManager.GetString("M000081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one report option..
        /// </summary>
        internal static string M000082 {
            get {
                return ResourceManager.GetString("M000082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Fail. Unable to sign on..
        /// </summary>
        internal static string M000083 {
            get {
                return ResourceManager.GetString("M000083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name cannot be blank.
        /// </summary>
        internal static string M000084 {
            get {
                return ResourceManager.GetString("M000084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Exported Successfully.
        /// </summary>
        internal static string M000085 {
            get {
                return ResourceManager.GetString("M000085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Imported Successfully.
        /// </summary>
        internal static string M000086 {
            get {
                return ResourceManager.GetString("M000086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Corrupted.
        /// </summary>
        internal static string M000087 {
            get {
                return ResourceManager.GetString("M000087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Schedule File.
        /// </summary>
        internal static string M000088 {
            get {
                return ResourceManager.GetString("M000088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected meters cannot be left blank.
        /// </summary>
        internal static string M000089 {
            get {
                return ResourceManager.GetString("M000089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Group from the Tree.
        /// </summary>
        internal static string M000090 {
            get {
                return ResourceManager.GetString("M000090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgroup Name Already Available.
        /// </summary>
        internal static string M000091 {
            get {
                return ResourceManager.GetString("M000091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated Successfully.
        /// </summary>
        internal static string M000092 {
            get {
                return ResourceManager.GetString("M000092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        internal static string M000093 {
            get {
                return ResourceManager.GetString("M000093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubGroup Name &quot;All&quot; already exists.Cannot be added.
        /// </summary>
        internal static string M000094 {
            get {
                return ResourceManager.GetString("M000094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubGroup Name cannot be blank.
        /// </summary>
        internal static string M000095 {
            get {
                return ResourceManager.GetString("M000095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubGroup Name &quot;All&quot; cannot be deleted.
        /// </summary>
        internal static string M000096 {
            get {
                return ResourceManager.GetString("M000096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts exceeded. Access Denied..
        /// </summary>
        internal static string M000097 {
            get {
                return ResourceManager.GetString("M000097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be empty.
        /// </summary>
        internal static string M000098 {
            get {
                return ResourceManager.GetString("M000098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule file corrupted..
        /// </summary>
        internal static string M000099 {
            get {
                return ResourceManager.GetString("M000099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter SIM number should be 10 digits long..
        /// </summary>
        internal static string M000100 {
            get {
                return ResourceManager.GetString("M000100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can accept only Numbers from 0-9.
        /// </summary>
        internal static string M000101 {
            get {
                return ResourceManager.GetString("M000101", resourceCulture);
            }
        }
    }
}
