//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHANNEL.Formatter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParseFDLResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParseFDLResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHANNEL.Formatter.ParseFDLResource", typeof(ParseFDLResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC mismatch in billing data..
        /// </summary>
        internal static string BCCMismatchBilling {
            get {
                return ResourceManager.GetString("BCCMismatchBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC mismatch in general data..
        /// </summary>
        internal static string BCCMismatchGeneral {
            get {
                return ResourceManager.GetString("BCCMismatchGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC mismatch in instantaneous data..
        /// </summary>
        internal static string BCCMismatchInstantaneous {
            get {
                return ResourceManager.GetString("BCCMismatchInstantaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC mismatch in load survey data..
        /// </summary>
        internal static string BCCMismatchLS {
            get {
                return ResourceManager.GetString("BCCMismatchLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC mismatch in Mid Night data..
        /// </summary>
        internal static string BCCMismatchMidNight {
            get {
                return ResourceManager.GetString("BCCMismatchMidNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC mismatch in tamper data..
        /// </summary>
        internal static string BCCMismatchTamper {
            get {
                return ResourceManager.GetString("BCCMismatchTamper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading Billing data.
        /// </summary>
        internal static string BillingPacketsStatus {
            get {
                return ResourceManager.GetString("BillingPacketsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading Billing Data.
        /// </summary>
        internal static string BillingStatus {
            get {
                return ResourceManager.GetString("BillingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading General Data.
        /// </summary>
        internal static string GeneralStatus {
            get {
                return ResourceManager.GetString("GeneralStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading Instantaneous Data.
        /// </summary>
        internal static string InstantaneousStatus {
            get {
                return ResourceManager.GetString("InstantaneousStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading Load Survey Data.
        /// </summary>
        internal static string LSPacketsStatus {
            get {
                return ResourceManager.GetString("LSPacketsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading Midnight Data.
        /// </summary>
        internal static string MidnightStatus {
            get {
                return ResourceManager.GetString("MidnightStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading Tamper Data.
        /// </summary>
        internal static string TamperPacketsStatus {
            get {
                return ResourceManager.GetString("TamperPacketsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Uploading TOU Configuration Data.
        /// </summary>
        internal static string TOUStatus {
            get {
                return ResourceManager.GetString("TOUStatus", resourceCulture);
            }
        }
    }
}
