//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class TAMPERMAPPER
{

    private TAMPERMAPPERMAP[] mAPField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MAP")]
    public TAMPERMAPPERMAP[] MAP
    {
        get
        {
            return this.mAPField;
        }
        set
        {
            this.mAPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TAMPERMAPPERMAP
{

    private string dLMSCODEField;

    private string iECCODEField;

    private string dLMSRESCODE;

    private bool oCCURENCEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DLMSCODE
    {
        get
        {
            return this.dLMSCODEField;
        }
        set
        {
            this.dLMSCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IECCODE
    {
        get
        {
            return this.iECCODEField;
        }
        set
        {
            this.iECCODEField = value;
        }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DLMSRESCODE
    {
        get
        {
            return this.dLMSRESCODE;
        }
        set
        {
            this.dLMSRESCODE = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool OCCURENCE
    {
        get
        {
            return this.oCCURENCEField;
        }
        set
        {
            this.oCCURENCEField = value;
        }
    }
}
