
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace LNG.Entity
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class StructureUnitInformation
    {

        private StructureUnitEntity[] structureInfoEntityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StructureUnitEntity")]
        public StructureUnitEntity[] StructureUnitEntity
        {
            get
            {
                return this.structureInfoEntityField;
            }
            set
            {
                this.structureInfoEntityField = value;
            }
        }
    }
}
